# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: thestelllar
description: >- # this means to ignore newlines until "baseurl:"
    My Adventure Book Part I
baseurl: "/" # the subpath of the site
url: "https://thestelllar.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
    pages:
        - name: Home
          slug: /
        - name: Work
        - name: Blog

footer:
    show_powered_by: true
    contact:
        - name: Email
          value: thestelllar@gmail.com
          link: mailto:thestelllar@gmail.com
    follow:
        - name: Twitter
          link: http://twitter.com/thestelllar
          username: "@thestelllar"
        - name: LinkedIn
          link: https://www.linkedin.com/in/palak001/
        - name: GitHub
          link: http://github.com/thestelllar
        - name: RSS
          link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
    - jekyll-feed

# Excluded items
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - feed.xml
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/

# Used for defeating caching
version: 1
